[package]
name = "futuresdr-burn"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0"
burn = { version = "0.21", features = [
  "tui",
  "train",
  "vulkan",
  "webgpu",
  "autotune",
  "fusion",
] }
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../..", features = [
  "audio",
  "burn",
  "soapy",
] }
ndarray = "0.17" # has to align w/ the version from ndarray-npy
ndarray-npy = "0.10"
whisper-burn = { git = "https://github.com/bastibl/whisper-burn.git" }

[profile.release]
debug = true
