use std::future::Future;

use crate::runtime::BlockId;
use crate::runtime::Error;
use crate::runtime::Pmt;
use crate::runtime::PortId;
use crate::runtime::Result;
use crate::runtime::buffer::DynBufferReader;
use crate::runtime::buffer::DynBufferWriter;
use crate::runtime::buffer::PortInboxes;
use crate::runtime::dev::BlockMeta;
use crate::runtime::dev::MessageOutputs;
use crate::runtime::dev::WorkIo;

/// Send-capable proof for the generated block interface.
///
/// This keeps return-type-notation bounds for generated async handlers in one
/// place. Block authors should implement [`crate::runtime::dev::Kernel`], not
/// this trait.
#[doc(hidden)]
pub trait SendKernelInterface: KernelInterface + Send
where
    Self: KernelInterface<stream_ports_notify_finished(..): Send, call_handler(..): Send>,
{
}

impl<T> SendKernelInterface for T where
    T: KernelInterface<stream_ports_notify_finished(..): Send, call_handler(..): Send> + Send
{
}

/// Internal block interface generated by `#[derive(Block)]`.
///
/// Keep this as a structural bridge: generated code exposes concrete stream
/// fields, static message-port metadata, and message-handler dispatch. Runtime
/// behavior such as port initialization, validation, description collection,
/// and input finish handling belongs in the shared helper functions below and
/// in `WrappedKernel`.
#[doc(hidden)]
pub trait KernelInterface {
    /// Whether this block should run in a separate thread instead of on
    /// a normal scheduler worker.
    fn is_blocking() -> bool;
    /// Static block type name.
    fn type_name() -> &'static str;
    /// Visit all stream input ports.
    fn visit_stream_inputs(
        &mut self,
        f: &mut dyn FnMut(PortId, &mut dyn DynBufferReader) -> Result<(), Error>,
    ) -> Result<(), Error>;
    /// Visit all stream output ports.
    fn visit_stream_outputs(
        &mut self,
        f: &mut dyn FnMut(PortId, &mut dyn DynBufferWriter) -> Result<(), Error>,
    ) -> Result<(), Error>;
    /// Access one type-erased stream input by port id.
    fn with_stream_input<'a, R>(
        &'a mut self,
        id: &PortId,
        f: impl FnOnce(&'a mut dyn DynBufferReader) -> R,
    ) -> Result<R, Error>;
    /// Access one type-erased stream output by port id.
    fn with_stream_output<'a, R>(
        &'a mut self,
        id: &PortId,
        f: impl FnOnce(&'a mut dyn DynBufferWriter) -> R,
    ) -> Result<R, Error>;
    /// Notify adjacent stream peers that this block is done.
    ///
    /// This stays generated because concrete buffer `notify_finished` methods
    /// return `impl Future`; keeping the concrete calls here avoids boxing an
    /// object-safe notification path into every buffer implementation.
    fn stream_ports_notify_finished(&mut self) -> impl Future<Output = ()>;

    /// Message input port names.
    fn message_inputs() -> &'static [&'static str];
    /// Message output port names.
    fn message_outputs() -> &'static [&'static str];
    /// Call a message handler.
    fn call_handler(
        &mut self,
        _io: &mut WorkIo,
        _mo: &mut MessageOutputs,
        _meta: &mut BlockMeta,
        id: PortId,
        _p: Pmt,
    ) -> impl Future<Output = Result<Pmt, Error>>;
}

pub(crate) fn stream_inputs<K: KernelInterface>(kernel: &mut K) -> Result<Vec<String>, Error> {
    let mut names = Vec::new();
    kernel.visit_stream_inputs(&mut |name, _| {
        names.push(name.name().to_string());
        Ok(())
    })?;
    Ok(names)
}

pub(crate) fn stream_outputs<K: KernelInterface>(kernel: &mut K) -> Result<Vec<String>, Error> {
    let mut names = Vec::new();
    kernel.visit_stream_outputs(&mut |name, _| {
        names.push(name.name().to_string());
        Ok(())
    })?;
    Ok(names)
}

pub(crate) fn stream_ports_init<K: KernelInterface>(
    kernel: &mut K,
    block_id: BlockId,
    inboxes: PortInboxes,
) -> Result<(), Error> {
    kernel.visit_stream_inputs(&mut |name, port| {
        port.init_from(block_id, name, &inboxes);
        Ok(())
    })?;
    kernel.visit_stream_outputs(&mut |name, port| {
        port.init_from(block_id, name, &inboxes);
        Ok(())
    })
}

pub(crate) fn stream_ports_validate<K: KernelInterface>(kernel: &mut K) -> Result<(), Error> {
    kernel.visit_stream_inputs(&mut |_, port| port.validate())?;
    kernel.visit_stream_outputs(&mut |_, port| port.validate())
}

pub(crate) fn stream_input_finish<K: KernelInterface>(
    kernel: &mut K,
    port_id: PortId,
) -> Result<(), Error> {
    kernel.with_stream_input(&port_id, |port| port.finish())
}

pub(crate) fn stream_input<'a, K: KernelInterface>(
    kernel: &'a mut K,
    id: &PortId,
) -> Result<&'a mut dyn DynBufferReader, Error> {
    kernel.with_stream_input(id, |port| port)
}

pub(crate) fn stream_output<'a, K: KernelInterface>(
    kernel: &'a mut K,
    id: &PortId,
) -> Result<&'a mut dyn DynBufferWriter, Error> {
    kernel.with_stream_output(id, |port| port)
}
