use std::future::Future;

use crate::runtime::BlockId;
use crate::runtime::BlockPortCtx;
use crate::runtime::Error;
use crate::runtime::Pmt;
use crate::runtime::PortId;
use crate::runtime::PortIndex;
use crate::runtime::PortName;
use crate::runtime::Result;
use crate::runtime::buffer::DynBufferReader;
use crate::runtime::buffer::DynBufferWriter;
use crate::runtime::buffer::PortInboxes;
use crate::runtime::buffer::PortManifest;
use crate::runtime::dev::BlockMeta;
use crate::runtime::dev::MessageOutputs;
use crate::runtime::dev::WorkIo;

/// Internal block interface generated by `#[derive(Block)]`.
///
/// Keep this as a structural bridge: generated code exposes concrete stream
/// fields, static message-port metadata, and message-handler dispatch. Runtime
/// behavior such as port initialization, validation, description collection,
/// and input finish handling belongs in the shared helper functions below and
/// in `WrappedKernel`.
#[doc(hidden)]
pub trait KernelInterface {
    /// Whether this block should run in a separate thread instead of on
    /// a normal scheduler worker.
    fn is_blocking() -> bool;
    /// Static block type name.
    fn type_name() -> &'static str;
    /// Visit all stream input ports.
    fn visit_stream_inputs(
        &mut self,
        f: &mut dyn FnMut(PortId, &mut dyn DynBufferReader) -> Result<(), Error>,
    ) -> Result<(), Error>;
    /// Visit all stream output ports.
    fn visit_stream_outputs(
        &mut self,
        f: &mut dyn FnMut(PortId, &mut dyn DynBufferWriter) -> Result<(), Error>,
    ) -> Result<(), Error>;
    /// Access one type-erased stream input by port id.
    fn with_stream_input<'a, R>(
        &'a mut self,
        id: &PortId,
        f: impl FnOnce(&'a mut dyn DynBufferReader) -> R,
    ) -> Result<R, Error>;
    /// Access one type-erased stream output by port id.
    fn with_stream_output<'a, R>(
        &'a mut self,
        id: &PortId,
        f: impl FnOnce(&'a mut dyn DynBufferWriter) -> R,
    ) -> Result<R, Error>;
    /// Notify adjacent stream peers that this block is done.
    ///
    /// This stays generated because concrete buffer `notify_finished` methods
    /// return `impl Future`; keeping the concrete calls here avoids boxing an
    /// object-safe notification path into every buffer implementation.
    fn stream_ports_notify_finished(&mut self) -> impl Future<Output = ()>;

    /// Message input port names.
    fn message_inputs() -> &'static [&'static str];
    /// Message output port names.
    fn message_outputs() -> &'static [&'static str];
    /// Resolve a message input name to its dense per-block index.
    fn message_input_id(name: impl Into<PortName>) -> Option<PortIndex> {
        let name = name.into();
        Self::message_inputs()
            .iter()
            .position(|candidate| *candidate == name.as_str())
            .map(PortIndex::new)
    }
    /// Call a message handler.
    fn call_handler(
        &mut self,
        _io: &mut WorkIo,
        _mo: &mut MessageOutputs,
        _meta: &BlockMeta,
        id: PortIndex,
        _p: Pmt,
    ) -> impl Future<Output = Result<Pmt, Error>>;
}

pub(crate) fn stream_input_manifest<K: KernelInterface>(
    kernel: &mut K,
) -> Result<Vec<PortManifest>, Error> {
    let mut index = 0usize;
    let mut manifest = Vec::new();
    kernel.visit_stream_inputs(&mut |name, port| {
        manifest.push(PortManifest::input(
            name.name().to_string(),
            PortIndex::new(index),
            port,
        ));
        index += 1;
        Ok(())
    })?;
    Ok(manifest)
}

pub(crate) fn stream_output_manifest<K: KernelInterface>(
    kernel: &mut K,
) -> Result<Vec<PortManifest>, Error> {
    let mut index = 0usize;
    let mut manifest = Vec::new();
    kernel.visit_stream_outputs(&mut |name, port| {
        manifest.push(PortManifest::output(
            name.name().to_string(),
            PortIndex::new(index),
            port,
        ));
        index += 1;
        Ok(())
    })?;
    Ok(manifest)
}

pub(crate) fn stream_ports_init<K: KernelInterface>(
    kernel: &mut K,
    block_id: BlockId,
    inboxes: PortInboxes,
) -> Result<(), Error> {
    let mut index = 0usize;
    kernel.visit_stream_inputs(&mut |_name, port| {
        port.init_from(block_id, PortId::index(index), &inboxes);
        index += 1;
        Ok(())
    })?;
    let mut index = 0usize;
    kernel.visit_stream_outputs(&mut |_name, port| {
        port.init_from(block_id, PortId::index(index), &inboxes);
        index += 1;
        Ok(())
    })
}

pub(crate) fn stream_ports_validate<K: KernelInterface>(kernel: &mut K) -> Result<(), Error> {
    kernel.visit_stream_inputs(&mut |_, port| port.validate())?;
    kernel.visit_stream_outputs(&mut |_, port| port.validate())
}

fn stream_port_error_with_block_id(block_id: BlockId, error: Error) -> Error {
    match error {
        Error::InvalidStreamPort(BlockPortCtx::None, port) => {
            Error::InvalidStreamPort(BlockPortCtx::Id(block_id), port)
        }
        error => error,
    }
}

pub(crate) fn stream_input_finish<K: KernelInterface>(
    kernel: &mut K,
    block_id: BlockId,
    port_id: PortId,
) -> Result<(), Error> {
    kernel
        .with_stream_input(&port_id, |port| port.finish())
        .map_err(|error| stream_port_error_with_block_id(block_id, error))
}

pub(crate) fn stream_input<'a, K: KernelInterface>(
    kernel: &'a mut K,
    block_id: BlockId,
    id: &PortId,
) -> Result<&'a mut dyn DynBufferReader, Error> {
    kernel
        .with_stream_input(id, |port| port)
        .map_err(|error| stream_port_error_with_block_id(block_id, error))
}

pub(crate) fn stream_output<'a, K: KernelInterface>(
    kernel: &'a mut K,
    block_id: BlockId,
    id: &PortId,
) -> Result<&'a mut dyn DynBufferWriter, Error> {
    kernel
        .with_stream_output(id, |port| port)
        .map_err(|error| stream_port_error_with_block_id(block_id, error))
}

#[cfg(test)]
mod tests {
    use super::*;

    struct MissingPorts;

    impl KernelInterface for MissingPorts {
        fn is_blocking() -> bool {
            false
        }

        fn type_name() -> &'static str {
            "MissingPorts"
        }

        fn visit_stream_inputs(
            &mut self,
            _f: &mut dyn FnMut(PortId, &mut dyn DynBufferReader) -> Result<(), Error>,
        ) -> Result<(), Error> {
            Ok(())
        }

        fn visit_stream_outputs(
            &mut self,
            _f: &mut dyn FnMut(PortId, &mut dyn DynBufferWriter) -> Result<(), Error>,
        ) -> Result<(), Error> {
            Ok(())
        }

        fn with_stream_input<'a, R>(
            &'a mut self,
            id: &PortId,
            _f: impl FnOnce(&'a mut dyn DynBufferReader) -> R,
        ) -> Result<R, Error> {
            Err(Error::InvalidStreamPort(BlockPortCtx::None, id.clone()))
        }

        fn with_stream_output<'a, R>(
            &'a mut self,
            id: &PortId,
            _f: impl FnOnce(&'a mut dyn DynBufferWriter) -> R,
        ) -> Result<R, Error> {
            Err(Error::InvalidStreamPort(BlockPortCtx::None, id.clone()))
        }

        async fn stream_ports_notify_finished(&mut self) {}

        fn message_inputs() -> &'static [&'static str] {
            &[]
        }

        fn message_outputs() -> &'static [&'static str] {
            &[]
        }

        async fn call_handler(
            &mut self,
            _io: &mut WorkIo,
            _mo: &mut MessageOutputs,
            _meta: &BlockMeta,
            id: PortIndex,
            _p: Pmt,
        ) -> Result<Pmt, Error> {
            Err(Error::InvalidMessagePort(
                BlockPortCtx::None,
                PortId::from(id),
            ))
        }
    }

    #[test]
    fn stream_input_finish_invalid_port_reports_block_id() {
        let mut kernel = MissingPorts;
        let result = stream_input_finish(&mut kernel, BlockId(7), PortId::index(3));

        assert!(matches!(
            result,
            Err(Error::InvalidStreamPort(ctx, port))
                if ctx == BlockPortCtx::Id(BlockId(7)) && port == PortId::index(3)
        ));
    }

    #[test]
    fn stream_input_invalid_port_reports_block_id() {
        let mut kernel = MissingPorts;
        let result = stream_input(&mut kernel, BlockId(7), &PortId::index(3));

        assert!(matches!(
            result,
            Err(Error::InvalidStreamPort(ctx, port))
                if ctx == BlockPortCtx::Id(BlockId(7)) && port == PortId::index(3)
        ));
    }

    #[test]
    fn stream_output_invalid_port_reports_block_id() {
        let mut kernel = MissingPorts;
        let result = stream_output(&mut kernel, BlockId(7), &PortId::index(3));

        assert!(matches!(
            result,
            Err(Error::InvalidStreamPort(ctx, port))
                if ctx == BlockPortCtx::Id(BlockId(7)) && port == PortId::index(3)
        ));
    }
}
