[package]
name = "msg"
version = "0.1.0"
edition = "2024"
default-run = "msg"

[workspace]

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
core_affinity = "0.8"
futuresdr = { path = "../..", default-features = false, features = ["flow_scheduler"] }
tracing = { version = "0.1", features = ["release_max_level_off"] }

[[bin]]
name = "msg"
path = "msg.rs"

[[bin]]
name = "message-passing-overhead"
path = "message-passing-overhead.rs"
