[package]
name = "msg"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../.." }
tracing = { version = "0.1", features = ["release_max_level_off"] }

[[bin]]
name = "msg"
path = "msg.rs"
