{
 "title": "FutureSDR Dashboard",
 "description": "FutureSDR Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Raw Power vs Resampled Power",
   "type": "timeseries",
   "description": "Raw Power vs Resampled Power",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cw_gauge_level{type=\"pre_resample_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "agc_gauge_dB{type=\"input_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2. Clamp Block",
   "type": "timeseries",
   "description": "Clamp Block MEtrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cw_gauge_level{type=\"threshold\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "agc_gauge_dB{type=\"output_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cw_gauge_level{type=\"min_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cw_gauge_level{type=\"max_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1. AGC Block Metrics",
   "type": "timeseries",
   "description": "Visualization of the FutureSDR AGC Block metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "agc_gauge_dB{type=\"output_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "agc_gauge_dB{type=\"reference_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3. Clamp Block Output",
   "type": "timeseries",
   "description": "Clamp Block Output",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cw_gauge_level{type=\"clamped_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FutureSDR Debug Log",
   "type": "logs",
   "description": "FutureSDR Debug Log",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", level=\"INFO\"}"
    }
   ]
  }
 ]
}