[package]
name = "perf-burn"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0"
burn = { version = "0.21", features = [
  "vulkan",
  "webgpu",
  "autotune",
  "fusion",
] }
burn-cubecl = "0.21"
burn-fusion = "0.21"
burn-ir = "0.21"
burn-wgpu = "0.21"
bytemuck = "1.25"
bytes = "1"
cubecl = "0.10"
cubecl-runtime = "0.10"
futuresdr = { path = "../..", default-features = false, features = ["burn", "seify", "wgpu"] }
futuresdr-burn = { path = "../../examples/burn" }
ndarray = "0.17"
rustfft = "6.4"
tracing = { version = "0.1", default-features = false, features = ["release_max_level_off"] }
wgpu = "29.0"
