volumes:
  grafana:
  postgres:
services:
  # Grafana Alloy batches and processes traces sent to it, generating
  # auto-logs from those traces.
  # Includes Metrics, Logs, Traces and Profiles.
  alloy:
    image: grafana/alloy:v1.1.0
    container_name: alloy
    ports:
      - "4317:4317"
      - "12345:12345"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints.json:/etc/alloy/endpoints.json"
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--disable-reporting",
        # "--stability.level=public-preview",
        "/etc/alloy/config.alloy"
      ]
    networks:
      - futuresdr_telemetry

  # The Grafana dashboarding server.
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    volumes:
      - "./grafana/definitions/dashboards:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/main.json
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1ms
      - GF_METRICS_INTERVAL_SECONDS=50ms # Flush/write interval when sending metrics to external TSDB.
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - futuresdr_telemetry

  # The Tempo service stores traces send to it by Grafana Alloy, and takes
  # queries from Grafana to visualise those traces.
  tempo:
    image: grafana/tempo:latest #2.4.1
    container_name: tempo
    ports:
      - "3200:3200"
      - "44317:4317"
      - "44318:4318"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./tempo/tempo.yaml:/etc/tempo.yaml"
    networks:
     - futuresdr_telemetry

  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command:
      [
        "-config.file=/etc/loki/loki.yaml"
      ]
    ports:
      - "3100:3100"
    volumes:
      - "./loki/loki.yaml:/etc/loki/loki.yaml"
    networks:
      - futuresdr_telemetry

  mimir:
    image: grafana/mimir:latest #2.12.0
    container_name: mimir
    command:
      [
        "-config.file=/etc/mimir.yaml"
      ]
    ports:
      - "9009:9009"
    volumes:
      - "./mimir/mimir.yaml:/etc/mimir.yaml"
    networks:
     - futuresdr_telemetry

networks:
  futuresdr_telemetry:
    name: futuresdr-telemetry
    external: false