[package]
name = "wgpu"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "futuresdr_app"
path = "src/loopback.rs"

[dependencies]
anyhow = "1.0"
futuresdr = { path = "../..", features = ["wgpu"] }
rand = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen-futures = "0.4"
