[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false


[workspace]

[dependencies]
futuresdr = { path = "../..", features = ["telemetry"] }
tokio = {version = "1", features = ["macros", "rt-multi-thread"] }
