[package]
name = "firdes"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0"
futuresdr = { path = "../..", features = ["audio"] }
futuredsp = { path = "../../crates/futuredsp" }
