[package]
name = "prophecy"
version.workspace = true
authors = ["FutureSDR Contributors <team@futuresdr.org>"]
edition = "2024"
license = "Apache-2.0"
homepage = "https://www.futuresdr.org"
repository = "https://github.com/futuresdr/futuresdr/"
readme = "README.md"
description = "FutureSDR GUI"
keywords = ["sdr", "radio", "runtime", "async", "acceleration"]
categories = [
    "asynchronous",
    "concurrency",
    "hardware-support",
    "science",
    "wasm",
]

[dependencies]
any_spawner = { version = "0.3", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1"
futures = { version = "0.3", default-features = false, features = ["async-await", "std"] }
futuresdr.workspace = true
futuresdr-types.workspace = true
gloo-net = { version = "0.7", default-features = false, features = [
    "http",
    "json",
    "websocket",
] }
gloo-timers = { version = "0.4", features = ["futures"] }
indexmap = "2.14"
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr", "nightly"] }
num-complex = "0.4"
serde_json = "1"
thiserror = "2"
uuid = { version = "1.24", features = ["v4", "js"] }

[dependencies.web-sys]
version = "0.3"
features = [
    'DomRect',
    'Element',
    'HtmlCanvasElement',
    'HtmlElement',
    'HtmlInputElement',
    'HtmlSelectElement',
    'WheelEvent',
    'ImageData',
    'WebGlBuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGl2RenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
]
