[package]
name = "futuresdr-remote"
version.workspace = true
authors = ["FutureSDR Contributors <team@futuresdr.org>"]
edition = "2024"
license = "Apache-2.0"
homepage = "https://www.futuresdr.org"
repository = "https://github.com/futuresdr/futuresdr/"
description = "Remote interaction library for FutureSDR."
keywords = ["sdr", "radio", "runtime", "async", "acceleration"]
categories = ["asynchronous", "concurrency", "hardware-support", "science", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futuresdr-types.workspace = true
reqwest = { version = "0.13", features = ["json"] }
serde = "1.0"
thiserror = "2.0"

[dev-dependencies]
tokio = { version = "1", features = [ "macros", "rt", "rt-multi-thread"] }
