[package]
name = "spectrum"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cpu"

[features]
default = []
wgpu = ["futuresdr/wgpu"]


[[bin]]
name = "futuresdr_app"
path = "src/bin/web.rs"

[dependencies]
anyhow = "1.0"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
futuresdr = { path = "../..", features = ["hackrf", "hydrasdr"] }
gloo-net = { version = "0.7", default-features = false, features = ["websocket"] }
leptos = { version = "0.8", features = ["csr", "nightly"] }
prophecy = { path = "../../crates/prophecy" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futuresdr = { path = "../..", features = ["soapy"] }
